name = "LubySequence"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LubySequence"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
experimental.module = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
# rev = "master"
rev = "v4.27.0"

[[lean_lib]]
name = "LubySequence"

[[require]]
name = "doc-gen4"
scope = "leanprover"
# If you are developing against a release candidate or a stable version `v4.x`, replace `main` below by `v4.x`.
# If you do not use `main` keep in mind to update this field as you update your Lean version.
rev = "main"
